# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'SectionIndexView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #pod 'FQYSectionIndexView', '~> 0.0.2'
  #pod 'SectionIndexView'

end
